
-- Or just create a new DB named [FileInfo] using SSMS tool

USE [master]
GO

/****** Object:  Database [FileInfo]    Script Date: 1/16/2016 2:31:39 AM ******/
CREATE DATABASE [FileInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FileInfo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FileInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FileInfo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FileInfo] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FileInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FileInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FileInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FileInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FileInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [FileInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FileInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FileInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FileInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FileInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FileInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FileInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FileInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FileInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FileInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FileInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FileInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FileInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FileInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FileInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FileInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FileInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FileInfo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FileInfo] SET  MULTI_USER 
GO

ALTER DATABASE [FileInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FileInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FileInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FileInfo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FileInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FileInfo] SET  READ_WRITE 
GO


